.github/workflows/R-CMD-check.yaml, .github/workflows/pkgdown.yaml, DESCRIPTION, NEWS.md, R/s2-geography.R, data-raw/update-s2.R, inst/include/s2/s2region_coverer.h, inst/include/s2/util/gtl/compact_array.h, man/as_s2_geography.Rd, src/s2/s2region_coverer.cc
See #71 and https://cran.r-project.org/web/checks/check_results_s2.html
=> Fix CRAN check errors

R/s2-xptr.R, data-raw/update-s2.R, inst/include/s2/encoded_s2point_vector.h, tests/testthat/test-s2-xptr.R
- Verified that the warnings were reproduced in the original code by adding `-Wnested-anon-types` to CPP_FLAGS in `Makevars.in`
- Named the structs to silence the warnings
- Documented the approach in data-raw/update-s2.R
=> Fix nested anon type/union warning

src/Makevars.in, src/s2-transformers.cpp
Dear s2 team,
The Rcpp team is trying to move towards defining `STRICT_R_HEADERS` by default.  Please the issue ticket at  https://github.com/RcppCore/Rcpp/issues/1158 for motivation and history.  In late April and early May, we identified around 51 packages needing changes (which we generally sent by PR or, in case of no known git repo, emailed patch).  We are thrilled to report that  38 have already made the changes, including some on CRAN.  We also accomodated one first fix in Rcpp itself -- the `cfloat` (or `float.h`) header is needed for the floating limits such as `DBL_MAX`.   A common remaining issue is use of `PI`.
And it appears that your most recent package change introduced a mild regression.  One line of code refers to `PI` where `M_PI` would make us whole.  This PR changes …
=> Switch one PI to M_PI to support STRICT_R_HEADERS

src/s2-transformers.cpp, tests/testthat/test-s2-transformers.R
Makes sure that `.Normalize()` is called on points before creating the `PointGeography` (#119). This was already the case for non-aggregate centroids, which were created correctly.
=> make sure aggregate centroids normalize points

src/Makevars.ucrt, src/Makevars.win, tools/winlibs.R
Sync build with the openssl package, cf https://github.com/jeroen/openssl/commit/774956317d394dca99bbac54d5cf251f8971970e
=> Windows: update openssl + fix ucrt

src/absl/strings/internal/str_format/parser.cc, src/s2/s2edge_distances.cc, src/s2/s2edge_distances.h
As shown here: https://cran.r-project.org/web/checks/check_results_s2.html
Fixes #167.
=> Fix clang warning on clang14

src/s2geography/constructor.h
Fixes #190 to avoid reverse dependency mayhem (but in the future we should consider converting with `check = FALSE` which is a lot faster and a user can subsequently call `st_is_valid()` to check).
=> Disable polyline validation on construction

src/absl/strings/internal/string_constant.h
Fixes #199.
@gareth-d-ga Could you check to make sure this works? I think that `remotes::install_github("r-spatial/s2#200")` should install from this branch.
=> Fix build on intel compilers

NEWS.md, tests/testthat/test-s2-cell.R
Fixes the data frame test after https://github.com/paleolimbot/wk/pull/166 (fixes #205). Previously this was only a problem on r-devel but it now looks like this has been in a released version.
=> Fix data frame test

.Rbuildignore, .clang-format, .github/workflows/check-standard.yaml, .github/workflows/test-coverage.yaml, NEWS.md, src/s2geography/build.cc, src/s2geography/geography.h, tests/testthat/test-s2-transformers.R
As identified in https://github.com/r-spatial/sf/issues/2053. A minimal reprex is `s2::s2_union("MULTIPOLYGON EMPTY")`.
=> Fix the unary union of the empty multipolygon

src/s2geography/build.cc, src/s2geography/constructor.h
See https://releases.llvm.org/5.0.1/tools/clang/tools/extra/docs/clang-tidy/checks/readability-container-size-empty.html
=> Use .empty() over .size() comparisons to 0

src/s2geography/constructor.h
Unnecessary for "smart" pointers:
https://clang.llvm.org/extra/clang-tidy/checks/readability/redundant-smartptr-get.html
=> Remove redundant .get()

tests/testthat/test-s2-lnglat.R
Which now correctly distinguishes between NaN and NA
=> Fix test for dev waldo

src/absl/strings/cord.h
Closes #223.
This warning is occurring because Abseil does C++ trickery to inline character data into its "cord" data structure. S2 uses the "strings" module from Abseil for its logging and its text format parsing/generation. We explicitly turn off logging and don't use S2's text format and thus the piece of code in question is never called.
This "fix" just comments out the line and throws an exception if for some unforseen reason that method actually actually does get called. In that case the error should propagate up to the top level catch provided by Rcpp.
The real fix is to update Abseil; however, updating Abseil means we can no longer support C++11 (we're using the last version of Abseil that does support C++11; subsequent versions require C++14). That would mean that s2 (and its …
=> Patch cord.h to remove CRAN warning

R/s2-bounds.R, R/s2-cell.R, man/s2_boundary.Rd, man/s2_bounds_cap.Rd, man/s2_cell_is_valid.Rd, man/s2_contains.Rd, man/s2_geog_point.Rd, man/s2_plot.Rd
Closes #225.
I opted to change the documentation: everywhere else we pass values directly to S2 (e.g., level) even though those are 0-indexed, too. This also has the benefit of not breaking any existing usage.
=> Fix documentation for `k` in `s2_cell_child()`

src/Makevars.in, src/Makevars.ucrt, src/Makevars.win
For #232...I also have a winbuilder check queued because I realized there wasn't CXX_STD = CXX11 in Makevars.ucrt (this matters for OBJECTS, so maybe it matters for CXX_STD too).
=> Add CXX11 back

R/s2-cell.R, man/s2_cell.Rd
This PR removes a duplicated `s2_cell_sentinel()` definition. This function is originally defined on line 43-47, then defined (identically) for a second time on 55-60; this PR removes the latter definition.
Re-documenting then removes a duplicate `\alias{s2_cell_sentinel()}` from the man page (and website -- https://r-spatial.github.io/s2/ ). It also added `\method{as_s2_cell}{integer64}(x, ...)`, which seems to be unrelated to this PR, but I left as a change (assuming it's caused by some other changes or package updates).
=> Remove duplicated s2_cell_sentinel() definition

src/absl/base/internal/direct_mmap.h
Closes #251.
Tested via:
```
apk add R R-dev g++ linux-headers
R -e "install.packages(c('Rcpp', 'wk'), repos = 'https://cloud.r-project.org/')"
cd /s2 && R CMD INSTALL . --preclean
```
Upstream reference: https://github.com/abseil/abseil-cpp/commit/4500c2fada4e952037c59bd65e8be1ba0b29f21e
=> Apply Abseil patch to fix compile on Alpine Linux

src/Makevars.win
As per cran policies, this uses the openssl llibs from rtools when available.
=> Use openssl from rtools if available

tests/testthat/test-plot.R, tests/testthat/test-vctrs.R
Causing CI to fail for our very specific CI job that installs minimal dependencies and runs the tests!
=> Skip vctrs-optional tests

src/s2/s2region_coverer.h
- Apply the `__extension__ Candidate* children[0];  // Actual size may be 0, 4, 16, or 64 elements.` fix from the previous vendor of s2.
=> Fix check warnings identified by r-lib/containers checks

tests/testthat/test-s2-transformers.R
Unfortunately the package does not pass its tests with mingw-w64 v12 on Windows. Rtools45 still uses mingw-w64 v11 to allow time for packages to be fixed, so one needs to use an unreleased version to see this.
The problem is that v12 decided to switch many C math functions to UCRT from previously used internal implementation. In case of s2, the failure is caused by very small inaccuracies in `sin()` - they are within 1 ULP, so programs should be able to work with that (the C standard doesn't give any limits to accuracy of math functions).
The failure is:
```
── Failure ('test-s2-transformers.R:476:3'): s2_buffer() works ─────────────────
abs(y - x) < epsilon is not TRUE
`actual`:   FALSE
`expected`: TRUE 
Backtrace:
▆
1. └─s2:::expect_near(s2_area(ply, radius = 1), 4 * pi/2, epsilon = …
```
=> Increase tolerance to accommodate small inaccuracies in sin().

DESCRIPTION
Seems like the new version of s2 needs cmake:
https://github.com/r-hub/r-minimal/actions/runs/15082868021/job/42401779896#step:4:456
=> Need cmake to build

src/s2-constructors-formatters.cpp, tests/testthat/test-s2-constructors-formatters.R
Closes #281
In most of the package we use Rcpp, which throws for this case:
``` r
library(s2)
geog <- as_s2_geography("POINT (0 1)")
s2_area(unserialize(serialize(geog, NULL)))
#> Error: external pointer is not valid
```
<sup>Created on 2025-05-28 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
...but the `print()` goes through `wk_format()`, which used the C API directly.
=> fix: Check for null pointers when using `R_ExternalPtrAddr` directly

NEWS.md
Added the mention of serialization support to NEWS.md
I also explicitly mention the other big reason for having it in the first place — sending data across forks and  cluster sessions for parallel processing.
=> Add mention of serializations support to NEWS.md
